const stamp = new Date("2026-01-01T00:00:00Z");
const emptySeo = {
  seoTitleTr: "",
  seoTitleAr: "",
  seoDescriptionTr: "",
  seoDescriptionAr: "",
};
const timestamps = { createdAt: stamp, updatedAt: stamp };
const categoryTaxonomy: [string, string, string, string, string | null][] = [
  ["hair", "sac-bakimi", "Saç Bakımı", "العناية بالشعر", null],
  ["skin", "cilt-bakimi", "Cilt Bakımı", "العناية بالبشرة", null],
  ["oils", "dogal-yaglar", "Doğal Yağlar", "الزيوت الطبيعية", null],
  ["herbs", "bitkisel-urunler", "Bitkisel Ürünler", "المنتجات العشبية", null],
  [
    "food",
    "bal-ve-dogal-urunler",
    "Bal ve Doğal Ürünler",
    "العسل والمنتجات الطبيعية",
    null,
  ],
  ["soap", "kisisel-bakim", "Kişisel Bakım", "العناية الشخصية", null],
  [
    "cupping",
    "hacamat-malzemeleri",
    "Hacamat ve Hacamat Malzemeleri",
    "الحجامة ومستلزماتها",
    null,
  ],
  ["shampoos", "sampuanlar", "Şampuanlar", "الشامبو", "hair"],
  ["hair-serums", "sac-serumlari", "Saç Serumları", "سيرومات الشعر", "hair"],
  ["hair-oils", "sac-yaglari", "Saç Yağları", "زيوت الشعر", "hair"],
  ["hair-conditioners", "sac-kremleri", "Saç Kremleri", "كريمات الشعر", "hair"],
  [
    "hair-blends",
    "sac-bakim-karisimlari",
    "Saç Bakım Karışımları",
    "خلطات العناية بالشعر",
    "hair",
  ],
  ["creams", "kremler", "Kremler", "الكريمات", "skin"],
  ["serums", "cilt-serumlari", "Cilt Serumları", "سيرومات البشرة", "skin"],
  [
    "skin-cleansing",
    "cilt-temizligi",
    "Cilt Temizliği",
    "تنظيف البشرة",
    "skin",
  ],
  ["body-care", "vucut-bakimi", "Vücut Bakımı", "العناية بالجسم", "skin"],
  [
    "plant-oils",
    "bitkisel-yaglar",
    "Bitkisel Yağlar",
    "الزيوت النباتية",
    "oils",
  ],
  ["essential-oils", "ucucu-yaglar", "Uçucu Yağlar", "الزيوت العطرية", "oils"],
  ["oil-blends", "yag-karisimlari", "Yağ Karışımları", "خلطات الزيوت", "oils"],
  ["spices", "bitkiler", "Bitkiler", "الأعشاب", "herbs"],
  [
    "herbal-blends",
    "bitkisel-karisimlar",
    "Bitkisel Karışımlar",
    "الخلطات العشبية",
    "herbs",
  ],
  [
    "herbal-extracts",
    "bitkisel-ekstraktlar",
    "Bitkisel Ekstraktlar",
    "المستخلصات العشبية",
    "herbs",
  ],
  ["honey", "bal", "Bal", "العسل", "food"],
  [
    "honey-blends",
    "balli-karisimlar",
    "Ballı Karışımlar",
    "خلطات العسل",
    "food",
  ],
  [
    "natural-foods",
    "dogal-gida-urunleri",
    "Doğal Gıda Ürünleri",
    "المنتجات الغذائية الطبيعية",
    "food",
  ],
  ["soaps", "sabunlar", "Sabunlar", "الصابون", "soap"],
  ["deodorants", "deodorantlar", "Deodorantlar", "مزيلات العرق", "soap"],
  ["daily-care", "gunluk-bakim", "Günlük Bakım", "العناية اليومية", "soap"],
  [
    "cupping-cups",
    "hacamat-kupalari",
    "Hacamat Kupaları",
    "كاسات الحجامة",
    "cupping",
  ],
  [
    "cupping-pump",
    "hacamat-pompasi",
    "Hacamat Pompası",
    "مضخة الحجامة",
    "cupping",
  ],
  [
    "cupping-sets",
    "hacamat-setleri",
    "Hacamat Setleri",
    "أطقم الحجامة",
    "cupping",
  ],
  [
    "cupping-accessories",
    "hacamat-aksesuarlari",
    "Hacamat Aksesuarları",
    "إكسسوارات الحجامة",
    "cupping",
  ],
  [
    "hygiene-consumables",
    "hijyen-ve-sarf-malzemeleri",
    "Hijyen ve Sarf Malzemeleri",
    "مستلزمات النظافة والاستهلاك",
    "cupping",
  ],
];
export const demoCategories = categoryTaxonomy.map(
  ([id, slug, nameTr, nameAr, parentId], sortOrder) => ({
    ...emptySeo,
    id,
    slug,
    nameTr,
    nameAr,
    image: "/images/botanical.webp",
    sortOrder,
    parentId,
    active: true,
    descriptionTr: "Günlük bakımınıza eşlik eden özenli bir seçki.",
    descriptionAr: "مجموعة مختارة بعناية لترافق روتينك اليومي.",
    ...timestamps,
  }),
);
export const demoTags = [
  ["hair-loss", "sac-dokulmesi", "Saç Dökülmesi", "تساقط الشعر"],
  ["dandruff", "kepek", "Kepek", "القشرة"],
  ["dry-hair", "kuru-sac", "Kuru Saç", "الشعر الجاف"],
  ["hair-care", "sac-bakimi", "Saç Bakımı", "العناية بالشعر"],
  [
    "scalp-care",
    "sac-derisi-bakimi",
    "Saç Derisi Bakımı",
    "العناية بفروة الرأس",
  ],
  ["moisture", "cilt-nemlendirme", "Cilt Nemlendirme", "ترطيب البشرة"],
  ["oily-skin", "yagli-cilt", "Yağlı Cilt", "البشرة الدهنية"],
  ["dry-skin", "kuru-cilt", "Kuru Cilt", "البشرة الجافة"],
  ["simple", "cilt-bakimi", "Cilt Bakımı", "العناية بالبشرة"],
  ["daily", "gunluk-bakim", "Günlük Bakım", "العناية اليومية"],
  ["cupping", "hacamat", "Hacamat", "الحجامة"],
  [
    "cupping-supplies",
    "hacamat-malzemeleri",
    "Hacamat Malzemeleri",
    "مستلزمات الحجامة",
  ],
].map(([id, slug, nameTr, nameAr], sortOrder) => ({
  id,
  slug,
  nameTr,
  nameAr,
  sortOrder,
  active: true,
  ...timestamps,
}));
export const demoCollections = [
  {
    id: "ritual",
    slug: "gunluk-rituel",
    nameTr: "Günlük Ritüel",
    nameAr: "روتينك اليومي",
    descriptionTr: "Kendinize ayırdığınız küçük anlar.",
    descriptionAr: "لحظات صغيرة تخصصها لنفسك.",
    active: true,
    sortOrder: 0,
    ...timestamps,
  },
];
const rawProducts = [
  {
    id: "argan",
    slug: "argan-bakim-yagi",
    nameTr: "Argan Bakım Yağı",
    nameAr: "زيت الأرغان للعناية",
    shortTr: "Saç ve cilt ritüelinize yalın bir dokunuş.",
    shortAr: "لمسة بسيطة لروتين العناية بالشعر والبشرة.",
    categoryId: "hair-oils",
    price: 34900,
    oldPrice: 39900,
    size: "50 ml",
    image: "/images/oil.webp",
    ingredientsTr: "Argania Spinosa Kernel Oil.",
    ingredientsAr: "زيت نواة الأرغان.",
    featured: true,
    bestSeller: true,
    isNew: false,
  },
  {
    id: "rose",
    slug: "gul-bakim-serumu",
    nameTr: "Gül Bakım Serumu",
    nameAr: "سيروم الورد للعناية",
    shortTr: "Günlük bakımınıza eşlik eden hafif doku.",
    shortAr: "ملمس خفيف يرافق روتين العناية اليومي.",
    categoryId: "skin",
    price: 42900,
    oldPrice: null,
    size: "30 ml",
    image: "/images/serum.webp",
    ingredientsTr: "Örnek formül: Aqua, Glycerin, Rosa Damascena Flower Water.",
    ingredientsAr: "تركيبة تجريبية: ماء، غليسرين، ماء الورد الدمشقي.",
    featured: true,
    bestSeller: false,
    isNew: true,
  },
  {
    id: "jojoba",
    slug: "jojoba-bakim-yagi",
    nameTr: "Jojoba Bakım Yağı",
    nameAr: "زيت الجوجوبا للعناية",
    shortTr: "Az içerik, özenli bir bakım ritüeli.",
    shortAr: "مكونات بسيطة لروتين عناية مدروس.",
    categoryId: "oils",
    price: 28900,
    oldPrice: null,
    size: "50 ml",
    image: "/images/oil-detail.webp",
    ingredientsTr: "Simmondsia Chinensis Seed Oil.",
    ingredientsAr: "زيت بذور الجوجوبا.",
    featured: true,
    bestSeller: true,
    isNew: true,
  },
  {
    id: "botanical",
    slug: "bitkisel-sac-bakim-yagi",
    nameTr: "Bitkisel Saç Bakım Yağı",
    nameAr: "زيت نباتي للعناية بالشعر",
    shortTr: "Saç bakımında kendinize ayırdığınız zaman.",
    shortAr: "وقت تخصصه لنفسك وللعناية بشعرك.",
    categoryId: "hair-oils",
    price: 37900,
    oldPrice: null,
    size: "100 ml",
    image: "/images/oil.webp",
    ingredientsTr:
      "Örnek formül: Prunus Amygdalus Dulcis Oil, Argania Spinosa Kernel Oil.",
    ingredientsAr: "تركيبة تجريبية: زيت اللوز الحلو، زيت الأرغان.",
    featured: true,
    bestSeller: false,
    isNew: false,
  },
];
export const demoProducts = rawProducts.map((p, i) => ({
  ...p,
  sku: `DEMO-00${i + 1}`,
  descriptionTr: `${p.nameTr}, günlük bakım ritüelini keşfetmeniz için hazırlanmış örnek bir üründür. Görsel ve içerik temsilidir; satışa açılmadan önce gerçek ürün bilgileriyle değiştirilmelidir.`,
  descriptionAr: `${p.nameAr} منتج تجريبي لاستكشاف تجربة العناية. الصورة والمعلومات توضيحية ويجب استبدالها ببيانات المنتج الفعلية قبل البيع.`,
  usageTr: "Üreticinin ambalaj üzerindeki kullanım talimatlarını takip edin.",
  usageAr: "اتبع تعليمات الاستخدام الموجودة على عبوة الشركة المصنّعة.",
  warningsTr:
    "Yalnızca harici kullanım içindir. Göz ile temasından kaçının. Tahriş durumunda kullanmayı bırakın. Çocukların erişemeyeceği yerde saklayın.",
  warningsAr:
    "للاستخدام الخارجي فقط. تجنب ملامسة العينين. توقف عن الاستخدام عند التهيج. يُحفظ بعيدًا عن متناول الأطفال.",
  featuresTr: "Örnek ürün • Cam ambalaj",
  featuresAr: "منتج تجريبي • عبوة زجاجية",
  seoTitleTr: "",
  seoTitleAr: "",
  seoDescriptionTr: "",
  seoDescriptionAr: "",
  stock: 20,
  active: true,
  archived: false,
  images: [
    {
      id: `img-${i}`,
      productId: p.id,
      url: p.image,
      altTr: p.nameTr,
      altAr: p.nameAr,
      sortOrder: 0,
      ...timestamps,
    },
    {
      id: `img-${i}-2`,
      productId: p.id,
      url: "/images/oil-detail.webp",
      altTr: `${p.nameTr} detay`,
      altAr: `تفاصيل ${p.nameAr}`,
      sortOrder: 1,
      ...timestamps,
    },
  ],
  category: demoCategories.find((c) => c.id === p.categoryId)!,
  tags: [demoTags[i % 4]],
  collections: [demoCollections[0]],
  ...timestamps,
}));
export const demoSlides = [
  {
    id: "slide-one",
    titleTr: "Doğanın özü.\nBakımın en yalın hali.",
    titleAr: "خلاصة الطبيعة.\nالعناية في أبسط صورها.",
    descriptionTr:
      "Kendinize iyi gelen ritüeller, özenle seçilen içerikler. NARANJ dünyasını keşfedin.",
    descriptionAr:
      "روتين يرافق لحظاتك ومكونات مختارة بعناية. اكتشف عالم نارنج.",
    ctaTr: "Koleksiyonu keşfet",
    ctaAr: "اكتشف المجموعة",
    url: "/products",
    desktopImage: "/images/hero.webp",
    mobileImage: "/images/oil.webp",
    sortOrder: 0,
    active: true,
    ...timestamps,
  },
  {
    id: "slide-two",
    titleTr: "Küçük bir ritüel.\nKendinize özel bir an.",
    titleAr: "روتين بسيط.\nلحظة خاصة بك.",
    descriptionTr: "Doğal yağlarla günlük bakımınıza yeni bir dokunuş.",
    descriptionAr: "لمسة جديدة لروتينك اليومي مع الزيوت الطبيعية.",
    ctaTr: "Yağları keşfet",
    ctaAr: "اكتشف الزيوت",
    url: "/categories/dogal-yaglar",
    desktopImage: "/images/hero.webp",
    mobileImage: "/images/oil-detail.webp",
    sortOrder: 1,
    active: true,
    ...timestamps,
  },
];
export const demoArticles = [
  {
    id: "guide-one",
    slug: "bakim-rituelinizi-olusturun",
    titleTr: "Kendinize ait bir bakım ritüeli",
    titleAr: "روتين عناية يشبهك",
    excerptTr: "Daha fazla ürün değil, ihtiyacınıza uygun küçük adımlar.",
    excerptAr: "خطوات بسيطة تناسب احتياجاتك وترافق يومك.",
    bodyTr:
      "Bakım rutininizi oluştururken ürünün etiketini ve kullanım talimatlarını okuyarak başlayın.\n\nBir ürünü seçerken içeriği, ambalajı ve kişisel tercihlerinizi birlikte değerlendirin. Yeni ürünleri aynı anda eklemek yerine tek tek deneyin.\n\nCildinizde rahatsızlık fark ederseniz kullanmayı bırakın. Kişisel bakım ürünleri tıbbi tedavi yerine geçmez.",
    bodyAr:
      "ابدأ بقراءة ملصق المنتج وتعليمات استخدامه عند اختيار روتين العناية.\n\nتعرّف على المكونات والعبوة وتفضيلاتك الشخصية. جرّب المنتجات الجديدة تدريجيًا بدلًا من إضافتها جميعًا في الوقت نفسه.\n\nتوقف عن الاستخدام إذا لاحظت تهيجًا. منتجات العناية الشخصية لا تحل محل العلاج الطبي.",
    image: "/images/oil-detail.webp",
    author: "NARANJ",
    active: true,
    ...timestamps,
    ...emptySeo,
  },
  {
    id: "guide-two",
    slug: "urun-etiketini-okumak",
    titleTr: "İçeriğini tanı, bilinçli seç",
    titleAr: "تعرّف على المكونات واختر بوعي",
    excerptTr: "Ürün etiketlerine daha yakından bakmak için bir başlangıç.",
    excerptAr: "بداية بسيطة لفهم ملصقات منتجات العناية.",
    bodyTr:
      "Ürünün içerik listesini, kullanım şeklini ve saklama koşullarını kontrol edin.\n\nDoğal ifadesi, bir ürünün herkes için uygun olduğu anlamına gelmez. Bilinen hassasiyetlerinizi dikkate alın ve ihtiyaç duyduğunuzda bir uzmana danışın.",
    bodyAr:
      "راجع قائمة المكونات وطريقة الاستخدام وظروف الحفظ.\n\nوصف المنتج بالطبيعي لا يعني أنه مناسب للجميع. انتبه لحساسياتك المعروفة واستشر مختصًا عند الحاجة.",
    image: "/images/botanical.webp",
    author: "NARANJ",
    active: true,
    ...timestamps,
    ...emptySeo,
  },
];
export const demoSettings = {
  id: "main",
  whatsapp: "905340606911",
  email: "",
  phone: "",
  addressTr: "",
  addressAr: "",
  instagram: "https://www.instagram.com/mo8sy/",
  facebook: "https://www.facebook.com/mo8sy",
  announcementTr: "Doğadan ilham alan günlük bakım ritüelleri",
  announcementAr: "روتين عناية يومي مستوحى من الطبيعة",
  seoTitleTr: "NARANJ | Doğadan gelen bakım",
  seoTitleAr: "نارنج | العناية المستوحاة من الطبيعة",
  seoDescriptionTr:
    "Doğal yağlar ve günlük bakım ürünleri. NARANJ seçkisini keşfedin, listenizi oluşturun ve WhatsApp üzerinden iletişime geçin.",
  seoDescriptionAr:
    "اكتشف مجموعة نارنج من الزيوت ومنتجات العناية اليومية، أنشئ قائمة طلبك وتواصل عبر واتساب.",
  ...timestamps,
};
export const demoPages = [
  [
    "about",
    "NARANJ Hakkında",
    "عن نارنج",
    "NARANJ; bakım ve güzellik ürünleri, bitkisel ürünler ve karışımlar, bal ve doğal ürünler ile hacamat malzemelerini bir araya getiren bir mağazadır. Özenle seçilmiş ürünleri Türkçe ve Arapça, sade ve anlaşılır bir alışveriş deneyimiyle sunmayı amaçlıyoruz.\n\nAmacımız, müşterilerimizin ihtiyaç duyduğu ürünlere kolayca ulaşmasını sağlamak, ürünler hakkında açık bilgiler sunmak ve sipariş detaylarını WhatsApp üzerinden doğrudan tamamlayabilmektir.\n\nÖzenle Seçilmiş Ürünler\n\nFarklı ihtiyaçlara uygun ürünleri özenle seçerek sunuyoruz.\n\nKolay Alışveriş\n\nSade ve anlaşılır yapı sayesinde aradığınız ürüne kolayca ulaşabilirsiniz.\n\nDoğrudan İletişim\n\nSipariş listenizi hazırlayıp WhatsApp üzerinden bizimle doğrudan iletişime geçebilirsiniz.",
    "نارنج متجر يهتم بمنتجات العناية والجمال والأعشاب والخلطات الطبيعية والعسل ومستلزمات الحجامة. نحرص على تقديم مجموعة متنوعة من المنتجات المختارة بعناية، مع تجربة تسوق بسيطة وواضحة باللغتين العربية والتركية.\n\nهدفنا أن يجد العميل المنتجات التي يحتاجها بسهولة، مع معلومات واضحة وإمكانية تجهيز الطلب والتواصل معنا مباشرة عبر واتساب لإتمام تفاصيل الطلب والشحن.\n\nمنتجات مختارة بعناية\n\nنحرص على اختيار وتقديم منتجات متنوعة تناسب احتياجات عملائنا.\n\nتجربة بسيطة\n\nتصفح واضح وسهل يساعدك على الوصول إلى المنتج المناسب بسرعة.\n\nتواصل مباشر\n\nيمكنك تجهيز قائمة طلبك والتواصل معنا مباشرة عبر واتساب.",
  ],
  [
    "contact",
    "Bizimle İletişime Geçin",
    "تواصل معنا",
    "Ürünler, fiyatlar, stok durumu, sipariş ve kargo detayları hakkında bilgi almak için bizimle iletişime geçebilirsiniz.\nSize uygun iletişim kanalını seçin, memnuniyetle yardımcı olalım.",
    "نسعد بتواصلكم معنا للاستفسار عن المنتجات، الأسعار، توفر المنتجات أو تفاصيل الطلب والشحن.\nاختر وسيلة التواصل المناسبة لك وسنكون سعداء بخدمتكم.",
  ],
  [
    "shipping",
    "Kargo Bilgileri",
    "معلومات الشحن",
    "Sipariş Hazırlığı\n\nWhatsApp üzerinden siparişinizi gönderdikten sonra ürünlerin stok durumu kontrol edilir ve sipariş detayları sizinle teyit edilir.\n\nKargo Ücreti\n\nKargo ücreti sipariş onaylanmadan önce müşteriye bildirilir. Ücret; kargo firması, şehir ve sipariş hacmine göre değişebilir.\n\nTeslimat Süresi\n\nTeslimat süresi şehre ve kargo firmasına göre değişebilir. Sipariş hazırlandıktan sonra mevcut teslimat bilgileri müşteriye iletilir.\n\nTeslimat Bilgileri\n\nGecikme yaşanmaması için ad, soyad, telefon numarası ve teslimat adresinin doğru iletilmesi gerekir.\n\nWeb sitesi üzerinden doğrudan ödeme alınmamaktadır. Sipariş ve kargo detayları WhatsApp üzerinden teyit edilir.",
    "تجهيز الطلب\n\nبعد إرسال طلبك عبر واتساب، يتم التأكد من توفر المنتجات ومراجعة تفاصيل الطلب معك.\n\nتكلفة الشحن\n\nيتم توضيح تكلفة الشحن للعميل قبل تأكيد الطلب، وقد تختلف حسب شركة الشحن والمدينة وحجم الطلب.\n\nمدة التوصيل\n\nتختلف مدة التوصيل حسب المدينة وشركة الشحن. يتم تزويد العميل بالمعلومات المتاحة بعد تجهيز الطلب.\n\nعنوان التوصيل\n\nيرجى التأكد من إرسال الاسم الكامل ورقم الهاتف والعنوان بشكل صحيح لتجنب أي تأخير في الشحنة.\n\nلا يتم تحصيل أي دفعات مباشرة من خلال الموقع. يتم تأكيد تفاصيل الطلب والشحن عبر واتساب.",
  ],
  [
    "returns",
    "İade ve Değişim",
    "الإرجاع والاستبدال",
    "İade Talebinden Önce\n\nİade veya değişim talebiniz için WhatsApp üzerinden bizimle iletişime geçerek sipariş ve ürün bilgilerini paylaşabilirsiniz.\n\nÜrünün Durumu\n\nÜrün; kullanılmamış, orijinal durumda, ambalajı ve varsa aksesuarlarıyla birlikte olmalıdır. Teslimatta hasarlı veya kusurlu ürünler ayrıca değerlendirilir.\n\nYanlış veya Hasarlı Ürün\n\nYanlış ya da hasarlı bir ürün teslim almanız durumunda mümkün olan en kısa sürede bizimle iletişime geçerek ürünün ve ambalajın açık fotoğraflarını paylaşınız.\n\nİadesi Uygun Olmayan Ürünler\n\nSağlık, kişisel bakım, hijyen veya güvenlik niteliği taşıyan bazı ürünler özel iade koşullarına tabi olabilir. İade uygunluğu ürünün niteliği, durumu ve yürürlükteki kurallar doğrultusunda değerlendirilir.",
    "قبل طلب الإرجاع\n\nيرجى التواصل معنا عبر واتساب وذكر رقم أو تفاصيل الطلب والمنتج المطلوب إرجاعه أو استبداله.\n\nحالة المنتج\n\nيجب أن يكون المنتج غير مستخدم وبحالته الأصلية وبتغليفه وملحقاته الأصلية، ما لم يكن سبب الطلب وجود عيب أو مشكلة في المنتج عند الاستلام.\n\nالمنتج الخاطئ أو المتضرر\n\nفي حال وصول منتج خاطئ أو متضرر، يرجى التواصل معنا في أقرب وقت وإرسال صور واضحة للمنتج والتغليف حتى نتمكن من مراجعة الحالة.\n\nالمنتجات غير المناسبة للإرجاع\n\nقد تخضع بعض المنتجات لأحكام خاصة بسبب طبيعتها الصحية أو الشخصية أو لأسباب تتعلق بالنظافة والسلامة. يتم تقييم أهلية الإرجاع وفق نوع المنتج وحالته والقواعد القانونية المعمول بها.",
  ],
  [
    "privacy",
    "Gizlilik Politikası",
    "سياسة الخصوصية",
    "Bu sayfa, sipariş ve iletişim süreçlerinde bilgilerin nasıl kullanıldığını açıklar.\n\nKullandığımız Bilgiler\n\nSiparişinizi hazırlamak ve sizinle iletişim kurmak için yalnızca gerekli bilgiler kullanılır; örneğin ad, telefon numarası ve teslimat adresi.\n\nSipariş Listesi ve Favoriler\n\nSipariş listeniz ve favori ürünleriniz, siteyi tekrar ziyaret ettiğinizde kullanım kolaylığı sağlamak amacıyla cihazınızda saklanabilir.\n\nWhatsApp Üzerinden İletişim\n\nWhatsApp ile iletişimi seçtiğinizde, seçtiğiniz sipariş bilgilerini göndermek üzere WhatsApp açılır. Mesaj sizin işleminiz olmadan gönderilmez.\n\nGizliliğin Korunması\n\nWeb sitesi üzerinden ödeme veya banka bilgileri talep edilmez. İletişim bilgileri yalnızca sipariş ve müşteri iletişimi amacıyla kullanılır.\n\nGizliliğiniz bizim için önemlidir. İletişim bilgileriniz satılmaz ve sipariş hizmeti dışındaki amaçlarla kullanılmaz.",
    "توضح هذه الصفحة كيفية استخدام المعلومات ضمن إجراءات الطلب والتواصل.\n\nالبيانات التي نستخدمها\n\nنستخدم فقط البيانات اللازمة لتجهيز طلبك والتواصل معك، مثل الاسم ورقم الهاتف وعنوان التوصيل عند تقديمه.\n\nقائمة الطلب والمفضلة\n\nقد يتم حفظ قائمة طلبك والمنتجات المفضلة على جهازك لتسهيل استخدام الموقع عند زيارتك مرة أخرى.\n\nالتواصل عبر واتساب\n\nعند اختيار التواصل عبر واتساب، يتم فتح واتساب لإرسال تفاصيل الطلب التي اخترتها. لا يقوم الموقع بإرسال الرسالة دون إجراء منك.\n\nحماية الخصوصية\n\nلا نطلب بيانات دفع أو معلومات مصرفية عبر الموقع، ونحرص على استخدام بيانات التواصل فقط لغرض خدمة الطلب والتواصل مع العميل.\n\nخصوصيتك مهمة لنا. لا يتم بيع بيانات التواصل الخاصة بك أو استخدامها لأغراض غير مرتبطة بخدمة الطلب.",
  ],
  [
    "terms",
    "Şartlar ve Koşullar",
    "الشروط والأحكام",
    "Sipariş sürecinin temel adımlarını ve onay öncesinde dikkat edilmesi gereken bilgileri burada bulabilirsiniz.\n\nÜrün Seçimi\n\nÜrünleri inceleyebilir, sipariş listenize ekleyebilir ve siparişi göndermeden önce miktarları ve detayları kontrol edebilirsiniz.\n\nSiparişin Gönderilmesi\n\nSipariş listesinin WhatsApp üzerinden gönderilmesi, ürünlerin kontrol edilmesi için bir iletişim talebidir ve satışın otomatik olarak tamamlandığı anlamına gelmez.\n\nFiyat ve Stok Onayı\n\nÜrünlerin stok durumu, fiyatları ve kargo ücreti sipariş kesinleşmeden önce müşteriyle teyit edilir.\n\nKargo ve Teslimat\n\nTeslimat süresi ve kargo ücreti şehir, kargo firması ve sipariş hacmine göre değişebilir. Mevcut bilgiler sipariş onayında müşteriye bildirilir.\n\nSiparişinizi onaylamadan önce ürünleri, miktarları, iletişim bilgilerini ve teslimat adresini dikkatlice kontrol ediniz.",
    "توضح هذه الصفحة الخطوات الأساسية للطلب والمعلومات التي ينبغي مراجعتها قبل التأكيد.\n\nاختيار المنتجات\n\nيمكنك تصفح المنتجات وإضافتها إلى قائمة طلبك، ثم مراجعة الكميات والتفاصيل قبل إرسال الطلب.\n\nإرسال الطلب\n\nإرسال قائمة الطلب عبر واتساب يُعد طلباً للتواصل والتحقق من المنتجات، ولا يعني إتمام البيع تلقائياً.\n\nتأكيد السعر والمخزون\n\nيتم تأكيد توفر المنتجات والأسعار وتكلفة الشحن مع العميل قبل اعتماد الطلب بشكل نهائي.\n\nالشحن والتسليم\n\nتختلف مدة وتكلفة الشحن حسب المدينة وشركة الشحن وحجم الطلب، ويتم توضيح التفاصيل المتاحة عند تأكيد الطلب.\n\nقبل تأكيد طلبك، يرجى مراجعة المنتجات والكميات وبيانات التواصل وعنوان التوصيل بعناية.",
  ],
  [
    "faq",
    "Sıkça Sorulan Sorular",
    "الأسئلة الشائعة",
    "NARANJ'dan nasıl sipariş verebilirim?\n\nİstediğiniz ürünleri sipariş listenize ekleyin. Daha sonra listenizi açıp \"WhatsApp ile Siparişi Tamamla\" seçeneğine dokunun. Sipariş özetiniz WhatsApp'ta hazır olarak açılır ve göndermeden önce kontrol edebilirsiniz.\n\nWeb sitesi üzerinden ödeme yapabilir miyim?\n\nHayır. Web sitesi üzerinden doğrudan ödeme alınmamaktadır. Sipariş ve kargo detayları WhatsApp üzerinden teyit edilir.\n\nÜrünün stokta olduğunu nasıl öğrenebilirim?\n\nÜrünün durumu web sitesinde gösterilir. Talep ettiğiniz miktarın kesin stok durumu siparişiniz WhatsApp üzerinden incelenirken teyit edilir.\n\nKargo ücretini nasıl öğrenebilirim?\n\nKargo ücreti sipariş, şehir ve kargo firmasına göre belirlenir ve sipariş onayından önce size bildirilir.\n\nSiparişimi değiştirebilir miyim?\n\nSiparişiniz henüz hazırlanmamış veya kargoya verilmemişse WhatsApp üzerinden bizimle iletişime geçebilirsiniz. Değişiklik imkânı sipariş durumuna göre değerlendirilir.\n\nNARANJ ile nasıl iletişime geçebilirim?\n\n\"İletişim\" sayfasındaki WhatsApp, Instagram veya Facebook bağlantılarından bize ulaşabilirsiniz.",
    "كيف أطلب من NARANJ؟\n\nأضف المنتجات التي تريدها إلى قائمة طلبك، ثم افتح القائمة واضغط على \"إتمام الطلب عبر واتساب\". سيتم فتح واتساب مع ملخص طلبك جاهزًا للمراجعة والإرسال.\n\nهل يمكن الدفع من خلال الموقع؟\n\nلا. الموقع لا يقوم بتحصيل الدفعات مباشرة. يتم التواصل معك عبر واتساب لتأكيد الطلب وتفاصيل الشحن.\n\nكيف أعرف أن المنتج متوفر؟\n\nيتم عرض حالة المنتج في الموقع، ويتم التأكد من توفر الكمية المطلوبة عند مراجعة الطلب عبر واتساب.\n\nكيف أعرف تكلفة الشحن؟\n\nيتم تحديد تكلفة الشحن حسب الطلب والمدينة وشركة الشحن وإبلاغك بها قبل تأكيد الطلب.\n\nهل يمكن تعديل الطلب؟\n\nإذا لم يتم تجهيز أو شحن الطلب بعد، تواصل معنا عبر واتساب وسنراجع إمكانية التعديل.\n\nكيف أتواصل مع NARANJ؟\n\nيمكنك التواصل معنا من خلال واتساب أو Instagram أو Facebook عبر صفحة \"تواصل معنا\".",
  ],
].map(([slug, titleTr, titleAr, bodyTr, bodyAr]) => ({
  id: slug,
  slug,
  titleTr,
  titleAr,
  bodyTr,
  bodyAr,
  ...timestamps,
}));
